In [1]:
import tensorflow as tf

tf.enable_eager_execution()

In [2]:
print(tf.add(1, 3))

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
print(tf.add([1, 2], [3, 4]))

tf.Tensor([4 6], shape=(2,), dtype=int32)


In [4]:
print(tf.square(4))

tf.Tensor(16, shape=(), dtype=int32)


In [7]:
x = tf.matmul([[1], [2]], [[2, 3]])
print(x.shape)
print(x.dtype)
print(x)

(2, 2)
<dtype: 'int32'>
tf.Tensor(
[[2 3]
 [4 6]], shape=(2, 2), dtype=int32)


In [9]:
tf.test.is_gpu_available()

False

In [10]:
x.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [23]:
data1 = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])
data2 = tf.data.TextLineDataset('tempfile.txt')

In [24]:
batch_data1 = data1.map(tf.square).shuffle(2).batch(2)
batch_data2 = data2.batch(2)

In [25]:
for i in batch_data1:
    print(i)

tf.Tensor([4 9], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([36  1], shape=(2,), dtype=int32)


In [26]:
for i in batch_data2:
    print(i)

tf.Tensor([b'line1..' b'line2...'], shape=(2,), dtype=string)
tf.Tensor([b'line3....' b'line'], shape=(2,), dtype=string)
